In [8]:
import numpy as np
an_array = np.array([3,33,333])
print(type(an_array))
print(an_array)

<class 'numpy.ndarray'>
[  3  33 333]


that was a numpy rank one example 

# below are some functions of nd arrays

In [4]:
print(an_array.shape)

(3,)


In [10]:
an_array[0] = 22
print(an_array)

[ 22  33 333]


now its time for rank 2 arrays

# rank two arrays

In [5]:
another = np.array([[1,2,3],[4,5,6]])
print(type(another))

<class 'numpy.ndarray'>


In [14]:
print(another.size)

6


In [16]:
print(another.shape)

(2, 3)


# other ways for creating arrays

In [19]:
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [22]:
ex2 = np.full((2,2),9)
print(ex2)

[[9 9]
 [9 9]]


In [24]:
ex3 = np.full((3,),10)
print(ex3)

[10 10 10]


In [27]:
ex4 = np.eye(2,2)
print(ex4)

[[1. 0.]
 [0. 1.]]


In [29]:
ex5 = np.ones((1,2))
print(ex5)

[[1. 1.]]


In [48]:
ex6 = np.random.random((2,2))
print(ex6)

[[0.32042731 0.62809719]
 [0.1993684  0.99747127]]


# nd array indexing

In [6]:
another = np.array([[1,2,3],[4,5,6],[3,6,7]])
print(another)

[[1 2 3]
 [4 5 6]
 [3 6 7]]


In [8]:
a = another[:2,1:3]
print(a)

[[2 3]
 [5 6]]


In [9]:
print(another[0,0])
print(a[0,0])

1
2


In [15]:
row = np.array([0,1,2])
col = np.array([0,1,2])
for ro,co in zip(row,col):
    print(ro,",",co)

0 , 0
1 , 1
2 , 2


In [24]:
another[row,col] += 10000
print(another)

[[90001     2     3]
 [    4 90005     6]
 [    3     6 90007]]


# boolean indexing

In [37]:
barr = np.array([[1,2,3,4],[45362,56,5,5],[7,89,64,3]])
barr[barr%2==0] = 0
print(barr)

[[ 1  0  3  0]
 [ 0  0  5  5]
 [ 7 89  0  3]]


# datatypes and Airthmatic Operations

In [9]:
dtarr = np.array([[1,2,3.4],[1,2.88,4]],dtype = np.int)
print(dtarr)

[[1 2 3]
 [1 2 4]]


In [44]:
print(dtarr+dtarr)
print(dtarr-dtarr)
print(dtarr*dtarr)
print(dtarr/dtarr)
print(np.sqrt(dtarr))
print(np.exp(dtarr))

[[2 4 6]
 [2 4 8]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 1  4 16]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.         1.41421356 1.73205081]
 [1.         1.41421356 2.        ]]
[[ 2.71828183  7.3890561  20.08553692]
 [ 2.71828183  7.3890561  54.59815003]]


# stastical sorting and sort operation